version: '3'

services:
  zk:
    # image: wurstmeister/zookeeper
    image: bitnami/zookeeper:3.7.0
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    networks:
      - kafka
  broker:
    # image: wurstmeister/kafka
    image: bitnami/kafka:2.8.0
    depends_on:
      - zk
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zk:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      # - JMX_PORT=9999
      - KAFKA_JMX_PORT=49999
    ports:
      - 9092:9092
    networks:
      - kafka
  gui:
    image: hlebalbau/kafka-manager:stable
    depends_on:
      - zk
    environment:
      - ZK_HOSTS=zk:2181
    ports:
      - 9000:9000
    networks:
      - kafka

networks:
  kafka:
    driver: bridge