version: '3'

services:
  redis-master1:
    build: buildredis
    networks:
      extnetwork:
        ipv4_address: 172.20.0.3
    ports:
      - 16379:6379

  redis-slave1:
    build: buildredis
    command: redis-server --slaveof redis-master1 6379
    networks:
      extnetwork:
        ipv4_address: 172.20.0.2
    ports:
      - 16378:6379
  
  redis-master2:
    build: buildredis
    networks:
      extnetwork:
        ipv4_address: 172.20.1.1
    ports:
      - 26379:6379

  redis-slave2:
    build: buildredis
    command: redis-server --slaveof redis-master2 6379
    networks:
      extnetwork:
        ipv4_address: 172.20.1.2
    ports:
      - 26378:6379

  redis-master3:
    build: buildredis
    networks:
      extnetwork:
        ipv4_address: 172.20.2.1
    ports:
      - 36379:6379

  redis-slave3:
    build: buildredis
    command: redis-server --slaveof redis-master3 6379
    networks:
      extnetwork:
        ipv4_address: 172.20.2.2
    ports:
      - 36378:6379
   
  redis-cluster-creator:
    container_name: redis-cluster-creator
    build: buildcluster
    networks:
      extnetwork:
    depends_on:
      - redis-master1
      - redis-slave1

  redis-sentinel1:
    build: sentinel
    networks:
      extnetwork:
    depends_on: 
      - redis-master1
      - redis-master2
      - redis-master3
      - redis-slave1
      - redis-slave2
      - redis-slave3

  redis-sentinel2:
    build: sentinel
    networks:
      extnetwork:
    depends_on: 
      - redis-master1
      - redis-master2
      - redis-master3
      - redis-slave1
      - redis-slave2
      - redis-slave3

  redis-sentinel3:
    build: sentinel
    networks:
      extnetwork:
    depends_on:
      - redis-master1
      - redis-master2
      - redis-master3
      - redis-slave1
      - redis-slave2
      - redis-slave3

networks:
   extnetwork:
      ipam:
         config:
         - subnet: 172.20.0.0/16